language: python
python:
- '3.8'

install:
- pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      before_script: pip install -r requirements-dev.txt
      script: |
        flake8 .
        black --check .
